# Generated by Django 5.0.2 on 2024-02-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField()),
                ('meeting_point', models.URLField()),
                ('drop_off_point', models.URLField()),
                ('review', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=120)),
                ('price_per_unit', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('header', models.CharField(max_length=350)),
                ('pic', models.ImageField(upload_to='uploads/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDetails',
            fields=[
                ('offer_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listing.offerinfo')),
                ('highlights', models.TextField()),
                ('including', models.TextField()),
                ('excluding', models.TextField()),
                ('faq', models.TextField()),
                ('description', models.TextField()),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
