# Generated by Django 5.0.2 on 2024-05-02 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=22)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Business description')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_pic', models.ImageField(upload_to='uploads/')),
                ('unit', models.CharField(max_length=120)),
                ('price_per_unit', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('header', models.CharField(max_length=350)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('disable_weekends', models.BooleanField(default=False)),
                ('disable_weekdays', models.BooleanField(default=False)),
                ('available_booking_months', models.PositiveIntegerField(default=1)),
                ('max_bookings_per_time', models.PositiveIntegerField()),
                ('period_of_each_booking', models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H'), ('210', '3H 30M'), ('240', '4H'), ('270', '4H 30M'), ('300', '5H'), ('360', '6H'), ('420', '7H'), ('480', '8H'), ('540', '9H'), ('600', '10H'), ('660', '11H'), ('720', '12H'), ('840', '14H'), ('960', '16H'), ('1080', '18H'), ('1440', '1D')], help_text='how much does each booking take', max_length=5)),
                ('highlights', models.TextField()),
                ('including', models.TextField()),
                ('excluding', models.TextField()),
                ('faq', models.TextField()),
                ('description', models.TextField()),
                ('additional_info', models.TextField()),
                ('location', models.CharField(max_length=600)),
                ('meeting_point', models.CharField(max_length=600)),
                ('drop_off_point', models.CharField(max_length=600)),
                ('review', models.URLField()),
                ('category', models.ManyToManyField(to='listing.category')),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='listing.pic')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.supplier')),
            ],
        ),
    ]
