# Generated by Django 5.0.2 on 2024-02-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Google',
            new_name='ThirdParty',
        ),
    ]
