# Generated by Django 5.0.2 on 2024-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='main_pic',
            field=models.ImageField(default='/uploads/red.jpg', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
