# Generated by Django 5.0.2 on 2024-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_offer_main_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='drop_off_point',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='offer',
            name='meeting_point',
            field=models.CharField(max_length=350),
        ),
    ]
