# Generated by Django 5.0.2 on 2024-02-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_rename_google_thirdparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerinfo',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerinfo',
            name='third_party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.thirdparty'),
            preserve_default=False,
        ),
    ]
