# Generated by Django 5.0.2 on 2024-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_offer_drop_off_point_alter_offer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='drop_off_point',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='offer',
            name='meeting_point',
            field=models.CharField(max_length=600),
        ),
    ]
