# Generated by Django 5.0.2 on 2024-03-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_offer_drop_off_point_alter_offer_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='available_booking_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='disable_weekdays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='disable_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_bookings_per_time',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='period_of_each_booking',
            field=models.CharField(choices=[('5', '5M'), ('10', '10M'), ('15', '15M'), ('20', '20M'), ('25', '25M'), ('30', '30M'), ('35', '35M'), ('40', '40M'), ('45', '45M'), ('60', '1H'), ('75', '1H 15M'), ('90', '1H 30M'), ('105', '1H 45M'), ('120', '2H'), ('150', '2H 30M'), ('180', '3H'), ('210', '3H 30M'), ('240', '4H'), ('270', '4H 30M'), ('300', '5H'), ('360', '6H'), ('420', '7H'), ('480', '8H'), ('540', '9H'), ('600', '10H'), ('660', '11H'), ('720', '12H'), ('840', '14H'), ('960', '16H'), ('1080', '18H'), ('1440', '1D')], default='180', help_text='how much does each booking take', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(to='listing.category'),
        ),
    ]
