# Generated by Django 5.0.5 on 2024-05-10 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='recap.user'),
        ),
    ]
